---
# defaults file for data-processing
neo4j_ip: 127.0.0.1
data_tag: master
model_file_name: bento_tailorx_model_file.yaml
properties_file_name: bento_tailorx_model_properties.yaml
dataset: Bento_Mock_Data_for_PACT1